spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://192.168.2.62:3307/mybatis
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource

    initialSize: 5
#    回收连接保证最小连接数
    minIdle: 5
#    连接池最多支持多少个会话
    maxActive: 20
#    请求连接最大等待时间
    maxWait: 60000
#    检查空闲连接的频率
    timeBetweenEvictionRunsMillis: 60000
#    池中某个连接的空闲时长达到 N 毫秒后, 连接池在下次检查空闲连接时 回收该连接
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 1 from dual
#    请求连接并池分配是否先检查连接有效
    testWhileIdle: true
#    申请连接有效性检查
    testOnBorrow: false
#    返还连接有效性检查
    testOnRuturn: false
#    缓存通过以下两个方法发起的sql
    poolPreparedStatements: true
    filters: stat,wall,log4j
#    每个连接最多缓存多少个SQL
    maxPoolPreparedStatementPerConnectionSize: 20
    useGlobalDataSourceStat: true
#    设置连接池统计方面配置
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
    schema:
      - classpath:sql/department.sql
      - classpath:sql/employee.sql
    initialization-mode: never
mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml